apiVersion: mygroup.myid.dev/v1alpha1
kind: MyResource
metadata:
  labels:
    app.kubernetes.io/name: myresource
    app.kubernetes.io/instance: myresource-sample
    app.kubernetes.io/part-of: kubebuilder-test
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-test
  name: myresource-sample
spec:
  # TODO(user): Add fields here
